name: openslide_4_0
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - openslide=4.0.0
  - jupyterlab
  - pydicom
  - pip
  - git
  - pip:
      - Pillow
      - ipywidgets
      - openslide-python==1.3.1
      - matplotlib
      - pyvips
      - minio
      - pandas
      - numpy
      - pyarrow
      - jupyterlab-lsp
      - jupyter-resource-usage
      - jedi-language-server
      - pathopatch==0.9.2b0
